"""add author id column

Revision ID: 9aae512bfc95
Revises: 2b3fe8f0bdb8
Create Date: 2023-06-08 21:30:06.529208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aae512bfc95'
down_revision = '2b3fe8f0bdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'genre_id')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
